apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-app
  labels:
    app: sparta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sparta-app
  template:
    metadata:
      labels:
        app: sparta-app
    spec:
      containers:
      - name: sparta-app
        image: ameenahriffin/spartaapp-server
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sparta-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: sparta-app
